# Generated by Django 6.0.3 on 2026-03-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('groupme', 'GroupMe'), ('instagram', 'Instagram'), ('linktree', 'Linktree'), ('discord', 'Discord'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('link', 'Generic Link')], default='link', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
