# Generated by Django 6.0.3 on 2026-03-15 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_communitylink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRewardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('groupme', 'GroupMe'), ('instagram', 'Instagram'), ('linktree', 'Linktree'), ('discord', 'Discord'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('link', 'Generic Link')], default='link', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('extra_points', models.PositiveIntegerField(default=0, help_text='Bonus points awarded when a user claims this link. 0 = no points.')),
                ('is_unique_per_user', models.BooleanField(default=True, help_text='Each user can earn points from this link at most once.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Reward Link',
                'verbose_name_plural': 'Global Reward Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SponsorOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, upload_to='sponsor_logos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sponsor Organization',
                'verbose_name_plural': 'Sponsor Organizations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['points_required'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.CreateModel(
            name='GlobalRewardLinkClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.PositiveIntegerField()),
                ('reward_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='rewards.globalrewardlink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'reward_link')},
            },
        ),
    ]
