# Generated by Django 6.0.3 on 2026-03-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_globalrewardlink_sponsororganization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityLink',
        ),
    ]
