# Generated by Django 6.0.3 on 2026-03-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggqrcode',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='common', max_length=12),
        ),
        migrations.AddField(
            model_name='eggqrcode',
            name='reward_message',
            field=models.TextField(blank=True, default='', help_text='Custom message shown to user upon redemption.'),
        ),
    ]
