# Generated by Django 6.0.3 on 2026-03-11 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0002_eggqrcode_rarity_eggqrcode_reward_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggqrcode',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Embeddable video URL (e.g. YouTube). Displayed instead of GIF if provided.'),
        ),
        migrations.CreateModel(
            name='EggLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='The URL the button will link to')),
                ('icon', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('groupme', 'GroupMe'), ('instagram', 'Instagram'), ('linktree', 'Linktree'), ('discord', 'Discord'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('link', 'Generic Link')], default='link', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which links are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('egg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='eggs.eggqrcode')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
