# Generated by Django 6.0.3 on 2026-03-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0004_rename_egglink_to_rewardlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggqrcode',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Embedded Youtube/Vimeo URL. Takes priority over GIF if set.'),
        ),
    ]
