# Generated by Django 6.0.3 on 2026-03-12 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0005_alter_eggqrcode_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardlink',
            name='extra_points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded when user claims this link. 0 = no points.'),
        ),
        migrations.AddField(
            model_name='rewardlink',
            name='is_unique_per_user',
            field=models.BooleanField(default=False, help_text='If True, each user can earn points from this link at most once.'),
        ),
        migrations.CreateModel(
            name='RewardLinkClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.PositiveIntegerField()),
                ('reward_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='eggs.rewardlink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_link_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'reward_link')},
            },
        ),
    ]
