# Generated by Django 6.0.3 on 2026-03-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0006_add_rewardlink_extra_points_and_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggqrcode',
            name='is_rickroll',
            field=models.BooleanField(default=False, help_text='If True, redirects the user to Rick Astley after redemption.'),
        ),
    ]
