# Generated by Django 6.0.3 on 2026-03-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0007_eggqrcode_is_rickroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggqrcode',
            name='custom_video_file',
            field=models.FileField(blank=True, default='', help_text='Upload a local video (e.g., .mp4) to be played as a reward.', upload_to='egg_videos/'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='bonus_points_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
