# Generated by Django 6.0.3 on 2026-03-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0008_eggqrcode_custom_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggqrcode',
            name='custom_video_file',
        ),
        migrations.AddField(
            model_name='eggqrcode',
            name='local_video_path',
            field=models.CharField(blank=True, default='', help_text='Path to a local video (e.g., "egg_videos/myvid.mp4") to be played as a reward.', max_length=255),
        ),
    ]
