# Generated by Django 6.0.3 on 2026-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0009_remove_eggqrcode_custom_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggqrcode',
            name='exported_to_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
