# Generated by Django 6.0.3 on 2026-03-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0011_alter_redemption_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardlinkclaim',
            name='reward_link',
        ),
        migrations.AlterUniqueTogether(
            name='rewardlinkclaim',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rewardlinkclaim',
            name='user',
        ),
        migrations.DeleteModel(
            name='RewardLink',
        ),
        migrations.DeleteModel(
            name='RewardLinkClaim',
        ),
    ]
